server:
  port: 9005
spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/live.huanghe.blog
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
      registry-fetch-interval-seconds: 10
#redis:
#  pool:
#    host: 47.100.28.233
#    port: 7000
#    password: mfoyouredis-1
#    timeout: 5000 # 连接超时时间（毫秒）
#    max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#    config:
#      minIdle: 1
#      maxIdle: 100
#      maxTotal: 1000
#      maxWaitMillis: 100000

# 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath*:live/huanghe/*/mapper/*.xml  # 注意:一定要对应mapper映射xml文件的所在路径
  type-aliases-package: live.huanghe.*.domain/*  # 注意:对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线自动转驼峰

jackson:
  date-format:  HH:mm:ss
  time-zone: GMT+0
auth-server-url: http://localhost:9002 # 授权服务地址
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      scope: all
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token #检查令牌

logging:
  level:
    org.springframework.security: debug